package types

import (
	sdk "github.com/cosmos/cosmos-sdk/types"
	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
)

var _ sdk.Msg = &MsgIncreaseBeam{}

// NewMsgIncreaseBeam Build a increase beam message based on parameters
func NewMsgIncreaseBeam(updater string, id string, amount int32) *MsgIncreaseBeam {
	return &MsgIncreaseBeam{
		Updater: updater,
		Id:      id,
		Amount:  amount,
	}
}

// Route dunno
func (msg MsgIncreaseBeam) Route() string {
	return RouterKey
}

// Type Return the message type
func (msg MsgIncreaseBeam) Type() string {
	return "IncreaseBeam"
}

// GetSigners Return the list of signers for the given message
func (msg *MsgIncreaseBeam) GetSigners() []sdk.AccAddress {
	updater, err := sdk.AccAddressFromBech32(msg.Updater)
	if err != nil {
		panic(err)
	}
	return []sdk.AccAddress{updater}
}

// GetSignBytes Return the generated bytes from the signature
func (msg *MsgIncreaseBeam) GetSignBytes() []byte {
	bz := ModuleCdc.MustMarshalJSON(msg)
	return sdk.MustSortJSON(bz)
}

// ValidateBasic Validate the message payload before dispatching to the local kv store
func (msg *MsgIncreaseBeam) ValidateBasic() error {
	// Ensure the address is correct and that we are able to acquire it
	_, err := sdk.AccAddressFromBech32(msg.Updater)
	if err != nil {
		return sdkerrors.Wrapf(sdkerrors.ErrInvalidAddress, "Invalid creator address (%s)", err)
	}

	if msg.Amount <= 0 {
		return sdkerrors.Wrapf(sdkerrors.ErrInvalidCoins, "Invalid amount: must be greater than 0")
	}
	return nil
}
