// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dfract/genesis.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	ModuleAccountBalance    []types.Coin `protobuf:"bytes,1,rep,name=module_account_balance,json=moduleAccountBalance,proto3" json:"module_account_balance" yaml:"module_account_balance"`
	Params                  Params       `protobuf:"bytes,2,opt,name=params,proto3" json:"params" yaml:"params"`
	WaitingProposalDeposits []*Deposit   `protobuf:"bytes,3,rep,name=waiting_proposal_deposits,json=waitingProposalDeposits,proto3" json:"waiting_proposal_deposits,omitempty"`
	WaitingMintDeposits     []*Deposit   `protobuf:"bytes,4,rep,name=waiting_mint_deposits,json=waitingMintDeposits,proto3" json:"waiting_mint_deposits,omitempty"`
	MintedDeposits          []*Deposit   `protobuf:"bytes,5,rep,name=minted_deposits,json=mintedDeposits,proto3" json:"minted_deposits,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7934cd6128e7315, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetModuleAccountBalance() []types.Coin {
	if m != nil {
		return m.ModuleAccountBalance
	}
	return nil
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetWaitingProposalDeposits() []*Deposit {
	if m != nil {
		return m.WaitingProposalDeposits
	}
	return nil
}

func (m *GenesisState) GetWaitingMintDeposits() []*Deposit {
	if m != nil {
		return m.WaitingMintDeposits
	}
	return nil
}

func (m *GenesisState) GetMintedDeposits() []*Deposit {
	if m != nil {
		return m.MintedDeposits
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "lum.network.dfract.GenesisState")
}

func init() { proto.RegisterFile("dfract/genesis.proto", fileDescriptor_d7934cd6128e7315) }

var fileDescriptor_d7934cd6128e7315 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x8b, 0xda, 0x40,
	0x18, 0xc6, 0x93, 0xda, 0x7a, 0x88, 0xfd, 0x03, 0x51, 0x5b, 0x4d, 0x69, 0x94, 0x40, 0x41, 0x28,
	0x9d, 0x41, 0x7b, 0xeb, 0xad, 0xa9, 0xa5, 0xf4, 0x50, 0x2a, 0xf6, 0x50, 0xe8, 0x25, 0x4c, 0x26,
	0xb3, 0x71, 0xd8, 0xcc, 0x4c, 0xc8, 0x4c, 0x74, 0xfd, 0x16, 0xfb, 0x95, 0xf6, 0xe6, 0xd1, 0xe3,
	0x9e, 0x64, 0xd1, 0x6f, 0xb0, 0x9f, 0x60, 0x31, 0x33, 0xae, 0x87, 0x15, 0xbc, 0x85, 0xe7, 0x7d,
	0x9e, 0xdf, 0x33, 0x6f, 0x78, 0x9d, 0x56, 0x72, 0x51, 0x20, 0xac, 0x60, 0x4a, 0x38, 0x91, 0x54,
	0x82, 0xbc, 0x10, 0x4a, 0xb8, 0x6e, 0x56, 0x32, 0xc0, 0x89, 0x5a, 0x88, 0xe2, 0x12, 0x68, 0x87,
	0xd7, 0x4a, 0x45, 0x2a, 0xaa, 0x31, 0xdc, 0x7f, 0x69, 0xa7, 0xe7, 0x63, 0x21, 0x99, 0x90, 0x30,
	0x46, 0x92, 0xc0, 0xf9, 0x30, 0x26, 0x0a, 0x0d, 0x21, 0x16, 0x94, 0x9b, 0x79, 0xd3, 0xf0, 0x73,
	0x54, 0x20, 0x66, 0xf0, 0xde, 0xa1, 0x34, 0x21, 0xb9, 0x90, 0x54, 0x69, 0x35, 0xb8, 0xa9, 0x39,
	0x2f, 0x7f, 0xea, 0x67, 0xfc, 0x55, 0x48, 0x11, 0x77, 0xee, 0xbc, 0x65, 0x22, 0x29, 0x33, 0x12,
	0x21, 0x8c, 0x45, 0xc9, 0x55, 0x14, 0xa3, 0x0c, 0x71, 0x4c, 0x3a, 0x76, 0xbf, 0x36, 0x68, 0x8c,
	0xba, 0x40, 0x97, 0x83, 0x7d, 0x39, 0x30, 0xe5, 0xe0, 0xbb, 0xa0, 0x3c, 0xfc, 0xb8, 0xda, 0xf4,
	0xac, 0xfb, 0x4d, 0xef, 0xc3, 0x12, 0xb1, 0xec, 0x6b, 0x70, 0x1a, 0x13, 0x4c, 0x5b, 0x7a, 0xf0,
	0x4d, 0xeb, 0xa1, 0x96, 0xdd, 0x5f, 0x4e, 0x5d, 0x3f, 0xb7, 0xf3, 0xac, 0x6f, 0x0f, 0x1a, 0x23,
	0x0f, 0x3c, 0xfd, 0x1d, 0x60, 0x52, 0x39, 0xc2, 0xb6, 0x29, 0x7a, 0xa5, 0x8b, 0x74, 0x2e, 0x98,
	0x1a, 0x80, 0xfb, 0xcf, 0xe9, 0x2e, 0x10, 0x55, 0x94, 0xa7, 0x51, 0x5e, 0x88, 0x5c, 0x48, 0x94,
	0x45, 0x66, 0x6b, 0xd9, 0xa9, 0x55, 0x5b, 0xbc, 0x3f, 0x45, 0x1f, 0x6b, 0xcf, 0xf4, 0x9d, 0x49,
	0x4f, 0x4c, 0xd8, 0xe8, 0xd2, 0xfd, 0xe3, 0xb4, 0x0f, 0x60, 0x46, 0xb9, 0x3a, 0x42, 0x9f, 0x9f,
	0x87, 0x36, 0x4d, 0xf2, 0x37, 0xe5, 0xea, 0x11, 0x38, 0x76, 0xde, 0xec, 0x41, 0x24, 0x39, 0xa2,
	0x5e, 0x9c, 0x47, 0xbd, 0xd6, 0x99, 0x03, 0x25, 0xfc, 0xb1, 0xda, 0xfa, 0xf6, 0x7a, 0xeb, 0xdb,
	0x77, 0x5b, 0xdf, 0xbe, 0xde, 0xf9, 0xd6, 0x7a, 0xe7, 0x5b, 0xb7, 0x3b, 0xdf, 0xfa, 0xff, 0x29,
	0xa5, 0x6a, 0x56, 0xc6, 0x00, 0x0b, 0x06, 0xb3, 0x92, 0x7d, 0x36, 0x40, 0x88, 0x67, 0x88, 0x72,
	0x78, 0x05, 0xcd, 0x49, 0xa8, 0x65, 0x4e, 0x64, 0x5c, 0xaf, 0x2e, 0xe2, 0xcb, 0x43, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc6, 0xe2, 0x17, 0x2e, 0x9e, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MintedDeposits) > 0 {
		for iNdEx := len(m.MintedDeposits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MintedDeposits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.WaitingMintDeposits) > 0 {
		for iNdEx := len(m.WaitingMintDeposits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WaitingMintDeposits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.WaitingProposalDeposits) > 0 {
		for iNdEx := len(m.WaitingProposalDeposits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WaitingProposalDeposits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ModuleAccountBalance) > 0 {
		for iNdEx := len(m.ModuleAccountBalance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ModuleAccountBalance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ModuleAccountBalance) > 0 {
		for _, e := range m.ModuleAccountBalance {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.WaitingProposalDeposits) > 0 {
		for _, e := range m.WaitingProposalDeposits {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.WaitingMintDeposits) > 0 {
		for _, e := range m.WaitingMintDeposits {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.MintedDeposits) > 0 {
		for _, e := range m.MintedDeposits {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleAccountBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModuleAccountBalance = append(m.ModuleAccountBalance, types.Coin{})
			if err := m.ModuleAccountBalance[len(m.ModuleAccountBalance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WaitingProposalDeposits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WaitingProposalDeposits = append(m.WaitingProposalDeposits, &Deposit{})
			if err := m.WaitingProposalDeposits[len(m.WaitingProposalDeposits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WaitingMintDeposits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WaitingMintDeposits = append(m.WaitingMintDeposits, &Deposit{})
			if err := m.WaitingMintDeposits[len(m.WaitingMintDeposits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintedDeposits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintedDeposits = append(m.MintedDeposits, &Deposit{})
			if err := m.MintedDeposits[len(m.MintedDeposits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
