// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: faucet/mining.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Mining struct {
	Minter   string     `protobuf:"bytes,1,opt,name=minter,proto3" json:"minter,omitempty"`
	LastTime time.Time  `protobuf:"bytes,2,opt,name=last_time,json=lastTime,proto3,stdtime" json:"last_time"`
	Total    types.Coin `protobuf:"bytes,3,opt,name=total,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total"`
}

func (m *Mining) Reset()         { *m = Mining{} }
func (m *Mining) String() string { return proto.CompactTextString(m) }
func (*Mining) ProtoMessage()    {}
func (*Mining) Descriptor() ([]byte, []int) {
	return fileDescriptor_c954a5e44ca7afec, []int{0}
}
func (m *Mining) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Mining) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Mining.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Mining) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mining.Merge(m, src)
}
func (m *Mining) XXX_Size() int {
	return m.Size()
}
func (m *Mining) XXX_DiscardUnknown() {
	xxx_messageInfo_Mining.DiscardUnknown(m)
}

var xxx_messageInfo_Mining proto.InternalMessageInfo

func (m *Mining) GetMinter() string {
	if m != nil {
		return m.Minter
	}
	return ""
}

func (m *Mining) GetLastTime() time.Time {
	if m != nil {
		return m.LastTime
	}
	return time.Time{}
}

func (m *Mining) GetTotal() types.Coin {
	if m != nil {
		return m.Total
	}
	return types.Coin{}
}

type MsgMintAndSend struct {
	Minter   string    `protobuf:"bytes,1,opt,name=minter,proto3" json:"minter,omitempty"`
	MintTime time.Time `protobuf:"bytes,2,opt,name=mint_time,json=mintTime,proto3,stdtime" json:"mint_time"`
}

func (m *MsgMintAndSend) Reset()         { *m = MsgMintAndSend{} }
func (m *MsgMintAndSend) String() string { return proto.CompactTextString(m) }
func (*MsgMintAndSend) ProtoMessage()    {}
func (*MsgMintAndSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_c954a5e44ca7afec, []int{1}
}
func (m *MsgMintAndSend) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMintAndSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMintAndSend.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMintAndSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintAndSend.Merge(m, src)
}
func (m *MsgMintAndSend) XXX_Size() int {
	return m.Size()
}
func (m *MsgMintAndSend) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintAndSend.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintAndSend proto.InternalMessageInfo

func (m *MsgMintAndSend) GetMinter() string {
	if m != nil {
		return m.Minter
	}
	return ""
}

func (m *MsgMintAndSend) GetMintTime() time.Time {
	if m != nil {
		return m.MintTime
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*Mining)(nil), "lum.network.faucet.Mining")
	proto.RegisterType((*MsgMintAndSend)(nil), "lum.network.faucet.MsgMintAndSend")
}

func init() { proto.RegisterFile("faucet/mining.proto", fileDescriptor_c954a5e44ca7afec) }

var fileDescriptor_c954a5e44ca7afec = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xbf, 0x4e, 0xeb, 0x30,
	0x14, 0x87, 0xe3, 0x7b, 0x45, 0xd5, 0x06, 0x89, 0x21, 0x20, 0x54, 0x3a, 0x24, 0x55, 0xa7, 0x4a,
	0x08, 0x9b, 0xc2, 0x13, 0xb4, 0x88, 0xb1, 0x4b, 0x61, 0x62, 0x41, 0x4e, 0xe2, 0xba, 0x56, 0x62,
	0x9f, 0xaa, 0x76, 0xf8, 0xf3, 0x16, 0x7d, 0x0e, 0x1e, 0x04, 0x75, 0xec, 0xc8, 0x44, 0x51, 0xfb,
	0x22, 0xc8, 0x76, 0x2a, 0x31, 0x31, 0x30, 0xe5, 0xc4, 0xe7, 0x7c, 0x3e, 0xdf, 0x4f, 0x0e, 0x8f,
	0xa7, 0xb4, 0xca, 0x98, 0x21, 0x52, 0x28, 0xa1, 0x38, 0x9e, 0x2f, 0xc0, 0x40, 0x14, 0x95, 0x95,
	0xc4, 0x8a, 0x99, 0x67, 0x58, 0x14, 0xd8, 0x0f, 0x74, 0x12, 0x0e, 0xc0, 0x4b, 0x46, 0xdc, 0x44,
	0x5a, 0x4d, 0x89, 0x11, 0x92, 0x69, 0x43, 0xe5, 0xdc, 0x43, 0x9d, 0x13, 0x0e, 0x1c, 0x5c, 0x49,
	0x6c, 0x55, 0x9f, 0xc6, 0x19, 0x68, 0x09, 0x9a, 0xa4, 0x54, 0x33, 0xf2, 0x34, 0x48, 0x99, 0xa1,
	0x03, 0x92, 0x81, 0x50, 0xbe, 0xdf, 0x7b, 0x47, 0x61, 0x63, 0xec, 0x76, 0x47, 0xa7, 0x61, 0x43,
	0x0a, 0x65, 0xd8, 0xa2, 0x8d, 0xba, 0xa8, 0xdf, 0x9a, 0xd4, 0x7f, 0xd1, 0x30, 0x6c, 0x95, 0x54,
	0x9b, 0x47, 0xbb, 0xb0, 0xfd, 0xaf, 0x8b, 0xfa, 0x87, 0x57, 0x1d, 0xec, 0x6d, 0xf0, 0xde, 0x06,
	0xdf, 0xef, 0x6d, 0x46, 0xcd, 0xd5, 0x67, 0x12, 0x2c, 0x37, 0x09, 0x9a, 0x34, 0x2d, 0x66, 0x1b,
	0x11, 0x0d, 0x0f, 0x0c, 0x18, 0x5a, 0xb6, 0xff, 0x3b, 0xfc, 0x0c, 0x7b, 0x2b, 0x6c, 0xad, 0x70,
	0x6d, 0x85, 0x6f, 0x40, 0xa8, 0xd1, 0xa5, 0xa5, 0xdf, 0x36, 0x49, 0x9f, 0x0b, 0x33, 0xab, 0x52,
	0x9c, 0x81, 0x24, 0x75, 0x04, 0xff, 0xb9, 0xd0, 0x79, 0x41, 0xcc, 0xeb, 0x9c, 0x69, 0x07, 0xe8,
	0x89, 0xbf, 0xb9, 0x57, 0x84, 0x47, 0x63, 0xcd, 0xc7, 0x42, 0x99, 0xa1, 0xca, 0xef, 0x98, 0xca,
	0x7f, 0xcb, 0x63, 0xab, 0x3f, 0xe4, 0xb1, 0x98, 0x6d, 0x8c, 0x6e, 0x57, 0xdb, 0x18, 0xad, 0xb7,
	0x31, 0xfa, 0xda, 0xc6, 0x68, 0xb9, 0x8b, 0x83, 0xf5, 0x2e, 0x0e, 0x3e, 0x76, 0x71, 0xf0, 0x70,
	0xfe, 0xc3, 0x5b, 0x53, 0x95, 0xa7, 0x25, 0x64, 0x85, 0x00, 0x92, 0xcd, 0xa8, 0x50, 0xe4, 0x85,
	0xd4, 0xcf, 0xed, 0x02, 0xa4, 0x0d, 0xb7, 0xee, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x4c,
	0x6d, 0x36, 0x05, 0x02, 0x00, 0x00,
}

func (m *Mining) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Mining) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Mining) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Total.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMining(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.LastTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.LastTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintMining(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	if len(m.Minter) > 0 {
		i -= len(m.Minter)
		copy(dAtA[i:], m.Minter)
		i = encodeVarintMining(dAtA, i, uint64(len(m.Minter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgMintAndSend) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMintAndSend) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMintAndSend) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.MintTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.MintTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintMining(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x12
	if len(m.Minter) > 0 {
		i -= len(m.Minter)
		copy(dAtA[i:], m.Minter)
		i = encodeVarintMining(dAtA, i, uint64(len(m.Minter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMining(dAtA []byte, offset int, v uint64) int {
	offset -= sovMining(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Mining) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Minter)
	if l > 0 {
		n += 1 + l + sovMining(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.LastTime)
	n += 1 + l + sovMining(uint64(l))
	l = m.Total.Size()
	n += 1 + l + sovMining(uint64(l))
	return n
}

func (m *MsgMintAndSend) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Minter)
	if l > 0 {
		n += 1 + l + sovMining(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.MintTime)
	n += 1 + l + sovMining(uint64(l))
	return n
}

func sovMining(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMining(x uint64) (n int) {
	return sovMining(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Mining) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMining
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Mining: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Mining: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Minter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMining
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMining
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Minter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMining
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMining
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.LastTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMining
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMining
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Total.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMining(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMining
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMining
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMintAndSend) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMining
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMintAndSend: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMintAndSend: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Minter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMining
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMining
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Minter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMining
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMining
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.MintTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMining(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMining
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMining
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMining(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMining
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMining
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMining
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMining
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMining
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMining
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMining        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMining          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMining = fmt.Errorf("proto: unexpected end of group")
)
