// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: faucet/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryMintAndSendRequest struct {
	Minter   string    `protobuf:"bytes,1,opt,name=minter,proto3" json:"minter,omitempty"`
	MintTime time.Time `protobuf:"bytes,2,opt,name=mint_time,json=mintTime,proto3,stdtime" json:"mint_time"`
}

func (m *QueryMintAndSendRequest) Reset()         { *m = QueryMintAndSendRequest{} }
func (m *QueryMintAndSendRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMintAndSendRequest) ProtoMessage()    {}
func (*QueryMintAndSendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e01ab1e3e8ff22, []int{0}
}
func (m *QueryMintAndSendRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMintAndSendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMintAndSendRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMintAndSendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMintAndSendRequest.Merge(m, src)
}
func (m *QueryMintAndSendRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMintAndSendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMintAndSendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMintAndSendRequest proto.InternalMessageInfo

func (m *QueryMintAndSendRequest) GetMinter() string {
	if m != nil {
		return m.Minter
	}
	return ""
}

func (m *QueryMintAndSendRequest) GetMintTime() time.Time {
	if m != nil {
		return m.MintTime
	}
	return time.Time{}
}

type QueryMintAndSendResponse struct {
	Total string `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (m *QueryMintAndSendResponse) Reset()         { *m = QueryMintAndSendResponse{} }
func (m *QueryMintAndSendResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMintAndSendResponse) ProtoMessage()    {}
func (*QueryMintAndSendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e01ab1e3e8ff22, []int{1}
}
func (m *QueryMintAndSendResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMintAndSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMintAndSendResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMintAndSendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMintAndSendResponse.Merge(m, src)
}
func (m *QueryMintAndSendResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMintAndSendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMintAndSendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMintAndSendResponse proto.InternalMessageInfo

func (m *QueryMintAndSendResponse) GetTotal() string {
	if m != nil {
		return m.Total
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryMintAndSendRequest)(nil), "sandblockio.chain.faucet.QueryMintAndSendRequest")
	proto.RegisterType((*QueryMintAndSendResponse)(nil), "sandblockio.chain.faucet.QueryMintAndSendResponse")
}

func init() { proto.RegisterFile("faucet/query.proto", fileDescriptor_32e01ab1e3e8ff22) }

var fileDescriptor_32e01ab1e3e8ff22 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0xcd, 0x3c, 0x78, 0x8f, 0xf7, 0xe6, 0xed, 0x86, 0x87, 0x86, 0x20, 0x69, 0xc9, 0xaa, 0x28,
	0xce, 0xd8, 0xfa, 0x05, 0x2d, 0xb8, 0x74, 0x61, 0x75, 0xe5, 0x46, 0x26, 0xe9, 0x34, 0x1d, 0x9a,
	0xcc, 0x4d, 0x33, 0x37, 0x6a, 0x11, 0x37, 0x7e, 0x41, 0xc1, 0xbd, 0x6b, 0x3f, 0xa5, 0xcb, 0x82,
	0x1b, 0x57, 0x2a, 0xad, 0x1f, 0x22, 0x93, 0x49, 0x40, 0x90, 0x2e, 0xdc, 0xdd, 0x3b, 0xf7, 0x9c,
	0x7b, 0xcf, 0x39, 0x43, 0xd9, 0x52, 0x36, 0x99, 0x42, 0xb1, 0x69, 0x54, 0xbd, 0xe5, 0x55, 0x0d,
	0x08, 0x2c, 0xb4, 0xd2, 0x2c, 0xd2, 0x02, 0xb2, 0xb5, 0x06, 0x9e, 0xad, 0xa4, 0x36, 0xdc, 0xa3,
	0xa2, 0x41, 0x0e, 0x90, 0x17, 0x4a, 0xb4, 0xb8, 0xb4, 0x59, 0x0a, 0xd4, 0xa5, 0xb2, 0x28, 0xcb,
	0xca, 0x53, 0xa3, 0xbb, 0x1c, 0x72, 0x68, 0x4b, 0xe1, 0xaa, 0xee, 0xf5, 0x41, 0x47, 0x93, 0x95,
	0x16, 0xd2, 0x18, 0x40, 0x89, 0x1a, 0x8c, 0xed, 0xa6, 0x0f, 0x33, 0xb0, 0x25, 0x58, 0x91, 0x4a,
	0xab, 0xbc, 0x0e, 0xf1, 0x76, 0x9c, 0x2a, 0x94, 0x63, 0x51, 0xc9, 0x5c, 0x9b, 0x16, 0xec, 0xb1,
	0x09, 0xd2, 0xfb, 0x2f, 0x1c, 0xe2, 0xb9, 0x36, 0x38, 0x35, 0x8b, 0x97, 0xca, 0x2c, 0xe6, 0x6a,
	0xd3, 0x28, 0x8b, 0xec, 0x1e, 0xbd, 0x2a, 0xb5, 0x41, 0x55, 0x87, 0x64, 0x48, 0x46, 0x37, 0xf3,
	0xae, 0x63, 0x53, 0x7a, 0xe3, 0xaa, 0x37, 0x4e, 0x6a, 0x78, 0x31, 0x24, 0xa3, 0xdb, 0x49, 0xc4,
	0xbd, 0x20, 0xde, 0xfb, 0xe0, 0xaf, 0x7a, 0x1f, 0xb3, 0xeb, 0xfd, 0x8f, 0x41, 0xb0, 0xfb, 0x39,
	0x20, 0xf3, 0x6b, 0x47, 0x73, 0x83, 0xe4, 0x09, 0x0d, 0xff, 0xbd, 0x6a, 0x2b, 0x30, 0x56, 0xb1,
	0x3b, 0x7a, 0x89, 0x80, 0xb2, 0xe8, 0xae, 0xfa, 0x66, 0xf2, 0x95, 0xd0, 0xcb, 0x96, 0xc2, 0xbe,
	0x10, 0x7a, 0xfb, 0x17, 0x8f, 0x8d, 0xf9, 0xb9, 0x74, 0xf9, 0x19, 0x67, 0xd1, 0xe4, 0x7f, 0x28,
	0x5e, 0x56, 0x32, 0xfa, 0xf4, 0xed, 0xf7, 0xe7, 0x8b, 0x84, 0x0d, 0x45, 0xd1, 0x94, 0x46, 0xe1,
	0x3b, 0xa8, 0xd7, 0xa2, 0xfb, 0x6b, 0xe7, 0x4b, 0x7c, 0xf0, 0xf1, 0x7c, 0x9c, 0x3d, 0xdb, 0x1f,
	0x63, 0x72, 0x38, 0xc6, 0xe4, 0xd7, 0x31, 0x26, 0xbb, 0x53, 0x1c, 0x1c, 0x4e, 0x71, 0xf0, 0xfd,
	0x14, 0x07, 0xaf, 0x1f, 0xe5, 0x1a, 0x57, 0x4d, 0xca, 0x33, 0x28, 0xdd, 0x96, 0xc7, 0xfd, 0x9a,
	0x56, 0x81, 0x78, 0xdf, 0xaf, 0xc3, 0x6d, 0xa5, 0x6c, 0x7a, 0xd5, 0x66, 0xf9, 0xf4, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x89, 0x18, 0x58, 0x06, 0x51, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	MintAndSend(ctx context.Context, in *QueryMintAndSendRequest, opts ...grpc.CallOption) (*QueryMintAndSendResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) MintAndSend(ctx context.Context, in *QueryMintAndSendRequest, opts ...grpc.CallOption) (*QueryMintAndSendResponse, error) {
	out := new(QueryMintAndSendResponse)
	err := c.cc.Invoke(ctx, "/sandblockio.chain.faucet.Query/MintAndSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	MintAndSend(context.Context, *QueryMintAndSendRequest) (*QueryMintAndSendResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) MintAndSend(ctx context.Context, req *QueryMintAndSendRequest) (*QueryMintAndSendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintAndSend not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_MintAndSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMintAndSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MintAndSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandblockio.chain.faucet.Query/MintAndSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MintAndSend(ctx, req.(*QueryMintAndSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sandblockio.chain.faucet.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintAndSend",
			Handler:    _Query_MintAndSend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "faucet/query.proto",
}

func (m *QueryMintAndSendRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMintAndSendRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMintAndSendRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.MintTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.MintTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintQuery(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if len(m.Minter) > 0 {
		i -= len(m.Minter)
		copy(dAtA[i:], m.Minter)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Minter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMintAndSendResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMintAndSendResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMintAndSendResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Total) > 0 {
		i -= len(m.Total)
		copy(dAtA[i:], m.Total)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Total)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryMintAndSendRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Minter)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.MintTime)
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryMintAndSendResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Total)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryMintAndSendRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMintAndSendRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMintAndSendRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Minter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Minter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.MintTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMintAndSendResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMintAndSendResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMintAndSendResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Total = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
