package types

import (
	sdk "github.com/cosmos/cosmos-sdk/types"
	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
)

var _ sdk.Msg = &MsgUpdateBeam{}

// NewMsgUpdateBeam Build a increase beam message based on parameters
func NewMsgUpdateBeam(updater string, id string, amount int64, status BeamState, reward *BeamSchemeReward, review *BeamSchemeReview) *MsgUpdateBeam {
	return &MsgUpdateBeam{
		Updater: updater,
		Id:      id,
		Amount:  amount,
		Status:  status,
		Reward:  reward,
		Review:  review,
	}
}

// Route dunno
func (msg MsgUpdateBeam) Route() string {
	return RouterKey
}

// Type Return the message type
func (msg MsgUpdateBeam) Type() string {
	return "UpdateBeam"
}

// GetSigners Return the list of signers for the given message
func (msg *MsgUpdateBeam) GetSigners() []sdk.AccAddress {
	updater, err := sdk.AccAddressFromBech32(msg.Updater)
	if err != nil {
		panic(err)
	}
	return []sdk.AccAddress{updater}
}

// GetSignBytes Return the generated bytes from the signature
func (msg *MsgUpdateBeam) GetSignBytes() []byte {
	bz := ModuleCdc.MustMarshalJSON(msg)
	return sdk.MustSortJSON(bz)
}

// ValidateBasic Validate the message payload before dispatching to the local kv store
func (msg *MsgUpdateBeam) ValidateBasic() error {
	// Ensure the address is correct and that we are able to acquire it
	_, err := sdk.AccAddressFromBech32(msg.Updater)
	if err != nil {
		return sdkerrors.Wrapf(sdkerrors.ErrInvalidAddress, "Invalid creator address (%s)", err)
	}

	if msg.Amount < 0 {
		return sdkerrors.Wrapf(sdkerrors.ErrInvalidCoins, "Invalid amount: must be greater than 0")
	}
	return nil
}
