package types

import (
	sdk "github.com/cosmos/cosmos-sdk/types"
	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
)

var _ sdk.Msg = &MsgUpdateBeam{}

// NewMsgUpdateBeam Build a increase beam message based on parameters
func NewMsgUpdateBeam(updater string, id string, amount *sdk.Coin, status BeamState, data *BeamData, cancelReason string, hideContent bool, closesAtBlock int32, claimExpiresAtBlock int32) *MsgUpdateBeam {
	return &MsgUpdateBeam{
		UpdaterAddress:      updater,
		Id:                  id,
		Amount:              amount,
		Status:              status,
		Data:                data,
		HideContent:         hideContent,
		CancelReason:        cancelReason,
		ClosesAtBlock:       closesAtBlock,
		ClaimExpiresAtBlock: claimExpiresAtBlock,
	}
}

// Route dunno
func (msg MsgUpdateBeam) Route() string {
	return RouterKey
}

// Type Return the message type
func (msg MsgUpdateBeam) Type() string {
	return "UpdateBeam"
}

// GetSigners Return the list of signers for the given message
func (msg *MsgUpdateBeam) GetSigners() []sdk.AccAddress {
	updater, err := sdk.AccAddressFromBech32(msg.GetUpdaterAddress())
	if err != nil {
		panic(err)
	}
	return []sdk.AccAddress{updater}
}

// GetSignBytes Return the generated bytes from the signature
func (msg *MsgUpdateBeam) GetSignBytes() []byte {
	bz := ModuleCdc.MustMarshalJSON(msg)
	return sdk.MustSortJSON(bz)
}

// ValidateBasic Validate the message payload before dispatching to the local kv store
func (msg *MsgUpdateBeam) ValidateBasic() error {
	// Ensure the address is correct and that we are able to acquire it
	_, err := sdk.AccAddressFromBech32(msg.GetUpdaterAddress())
	if err != nil {
		return sdkerrors.Wrapf(sdkerrors.ErrInvalidAddress, "Invalid creator address (%s)", err)
	}

	// If we have an amount, make sure it is not negative nor zero
	if msg.Amount != nil && msg.Amount.IsNegative() {
		return sdkerrors.Wrapf(sdkerrors.ErrInvalidCoins, "Invalid amount: must be greater or equal 0")
	}
	return nil
}
