// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lumnetwork/millions/draw_schedule.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/gogoproto/types"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DrawSchedule struct {
	InitialDrawAt time.Time     `protobuf:"bytes,1,opt,name=initial_draw_at,json=initialDrawAt,proto3,stdtime" json:"initial_draw_at"`
	DrawDelta     time.Duration `protobuf:"bytes,2,opt,name=draw_delta,json=drawDelta,proto3,stdduration" json:"draw_delta"`
}

func (m *DrawSchedule) Reset()         { *m = DrawSchedule{} }
func (m *DrawSchedule) String() string { return proto.CompactTextString(m) }
func (*DrawSchedule) ProtoMessage()    {}
func (*DrawSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c201df69e572476, []int{0}
}
func (m *DrawSchedule) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DrawSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DrawSchedule.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DrawSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawSchedule.Merge(m, src)
}
func (m *DrawSchedule) XXX_Size() int {
	return m.Size()
}
func (m *DrawSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_DrawSchedule proto.InternalMessageInfo

func (m *DrawSchedule) GetInitialDrawAt() time.Time {
	if m != nil {
		return m.InitialDrawAt
	}
	return time.Time{}
}

func (m *DrawSchedule) GetDrawDelta() time.Duration {
	if m != nil {
		return m.DrawDelta
	}
	return 0
}

func init() {
	proto.RegisterType((*DrawSchedule)(nil), "lumnetwork.millions.DrawSchedule")
}

func init() {
	proto.RegisterFile("lumnetwork/millions/draw_schedule.proto", fileDescriptor_1c201df69e572476)
}

var fileDescriptor_1c201df69e572476 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x31, 0x4f, 0x84, 0x30,
	0x1c, 0xc5, 0xa9, 0x83, 0x51, 0xd4, 0x98, 0xa0, 0xc3, 0xc9, 0x50, 0x8c, 0x8b, 0x2e, 0xd7, 0x26,
	0xfa, 0x09, 0x24, 0x24, 0x2e, 0x4e, 0xea, 0xe4, 0x72, 0x29, 0x50, 0xa1, 0xb1, 0xa5, 0x04, 0xfe,
	0x0d, 0xfa, 0x2d, 0x6e, 0x74, 0xf4, 0xe3, 0xdc, 0x78, 0xa3, 0x93, 0x1a, 0xf8, 0x22, 0x86, 0x02,
	0xb9, 0xc4, 0xdb, 0xda, 0xbc, 0xf7, 0x7e, 0xff, 0x97, 0xe7, 0x5e, 0x4a, 0xa3, 0x0a, 0x0e, 0x8d,
	0xae, 0x5e, 0xa9, 0x12, 0x52, 0x0a, 0x5d, 0xd4, 0x34, 0xad, 0x58, 0xb3, 0xa8, 0x93, 0x9c, 0xa7,
	0x46, 0x72, 0x52, 0x56, 0x1a, 0xb4, 0x77, 0xb2, 0x31, 0x92, 0xc9, 0xe8, 0x9f, 0x66, 0x3a, 0xd3,
	0x56, 0xa7, 0xfd, 0x6b, 0xb0, 0xfa, 0x38, 0xd3, 0x3a, 0x93, 0x9c, 0xda, 0x5f, 0x6c, 0x5e, 0x68,
	0x6a, 0x2a, 0x06, 0x42, 0x17, 0xa3, 0x1e, 0xfc, 0xd7, 0x41, 0x28, 0x5e, 0x03, 0x53, 0xe5, 0x60,
	0xb8, 0xf8, 0x44, 0xee, 0x61, 0x54, 0xb1, 0xe6, 0x71, 0xac, 0xe0, 0xdd, 0xbb, 0xc7, 0xa2, 0x10,
	0x20, 0x98, 0x5c, 0xd8, 0x6e, 0x0c, 0x66, 0xe8, 0x1c, 0x5d, 0x1d, 0x5c, 0xfb, 0x64, 0x60, 0x91,
	0x89, 0x45, 0x9e, 0x26, 0x56, 0xb8, 0xb7, 0xfa, 0x0e, 0x9c, 0xe5, 0x4f, 0x80, 0x1e, 0x8e, 0xc6,
	0x70, 0xcf, 0xbc, 0x05, 0x2f, 0x74, 0x5d, 0x4b, 0x49, 0xb9, 0x04, 0x36, 0xdb, 0xb1, 0xa0, 0xb3,
	0x2d, 0x50, 0x34, 0x96, 0x1e, 0x38, 0x1f, 0x3d, 0x67, 0xbf, 0x8f, 0x45, 0x7d, 0x2a, 0xbc, 0x5b,
	0xb5, 0x18, 0xad, 0x5b, 0x8c, 0x7e, 0x5b, 0x8c, 0x96, 0x1d, 0x76, 0xd6, 0x1d, 0x76, 0xbe, 0x3a,
	0xec, 0x3c, 0xcf, 0x33, 0x01, 0xb9, 0x89, 0x49, 0xa2, 0x15, 0x95, 0x46, 0xcd, 0xa7, 0x75, 0x93,
	0x9c, 0x89, 0x82, 0xbe, 0x6d, 0x56, 0x86, 0xf7, 0x92, 0xd7, 0xf1, 0xae, 0x3d, 0x78, 0xf3, 0x17,
	0x00, 0x00, 0xff, 0xff, 0x44, 0xc0, 0xbb, 0x8a, 0x89, 0x01, 0x00, 0x00,
}

func (m *DrawSchedule) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DrawSchedule) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DrawSchedule) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.DrawDelta, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.DrawDelta):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintDrawSchedule(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.InitialDrawAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.InitialDrawAt):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintDrawSchedule(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintDrawSchedule(dAtA []byte, offset int, v uint64) int {
	offset -= sovDrawSchedule(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DrawSchedule) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.InitialDrawAt)
	n += 1 + l + sovDrawSchedule(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.DrawDelta)
	n += 1 + l + sovDrawSchedule(uint64(l))
	return n
}

func sovDrawSchedule(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDrawSchedule(x uint64) (n int) {
	return sovDrawSchedule(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DrawSchedule) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDrawSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DrawSchedule: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DrawSchedule: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialDrawAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrawSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDrawSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDrawSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.InitialDrawAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrawDelta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDrawSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDrawSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDrawSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.DrawDelta, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDrawSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDrawSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDrawSchedule(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDrawSchedule
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDrawSchedule
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDrawSchedule
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDrawSchedule
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDrawSchedule
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDrawSchedule
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDrawSchedule        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDrawSchedule          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDrawSchedule = fmt.Errorf("proto: unexpected end of group")
)
