package types

import (
	errorsmod "cosmossdk.io/errors"
)

var (
	ErrUnmarshalFailure                  = errorsmod.Register(ModuleName, 1001, "unable to unmarshal data structure")
	ErrInvalidID                         = errorsmod.Register(ModuleName, 1002, "invalid unknown ID provided")
	ErrEntityOverride                    = errorsmod.Register(ModuleName, 1003, "ID already exists")
	ErrIllegalStateOperation             = errorsmod.Register(ModuleName, 1004, "Operation not allowed for the entity state")
	ErrInvalidParams                     = errorsmod.Register(ModuleName, 1005, "Invalid params")
	ErrPoolNotFound                      = errorsmod.Register(ModuleName, 1100, "Pool not found")
	ErrFailedToRegisterPool              = errorsmod.Register(ModuleName, 1101, "Failed to register pool")
	ErrPoolNotReady                      = errorsmod.Register(ModuleName, 1102, "Pool not ready")
	ErrPoolKilled                        = errorsmod.Register(ModuleName, 1103, "Pool killed")
	ErrInvalidPoolParams                 = errorsmod.Register(ModuleName, 1104, "Invalid pool params")
	ErrPoolEmptySplitDelegations         = errorsmod.Register(ModuleName, 1105, "Failed to compute split delegation")
	ErrPoolInvalidSplit                  = errorsmod.Register(ModuleName, 1106, "Invalid split provided")
	ErrFailedToUpdatePool                = errorsmod.Register(ModuleName, 1107, "Failed to update pool")
	ErrPoolIsLocal                       = errorsmod.Register(ModuleName, 1108, "Pool is local")
	ErrFailedToRestorePool               = errorsmod.Register(ModuleName, 1109, "Failed to restore pool")
	ErrValidatorNotFound                 = errorsmod.Register(ModuleName, 1110, "Validator not found in pool validator set")
	ErrValidatorNotDisabled              = errorsmod.Register(ModuleName, 1111, "Validator not disabled")
	ErrInvalidRedelegateRetryAddress     = errorsmod.Register(ModuleName, 1112, "Invalid redelegate retry address")
	ErrInvalidRedelegateState            = errorsmod.Register(ModuleName, 1113, "Invalid redelegate state")
	ErrValidatorNotRedelegated           = errorsmod.Register(ModuleName, 1114, "Validator not redelegated by gov prop")
	ErrInvalidDepositAmount              = errorsmod.Register(ModuleName, 1200, "Deposit amount must be positive")
	ErrInvalidDepositDenom               = errorsmod.Register(ModuleName, 1201, "Invalid deposit denom")
	ErrInvalidDepositorAddress           = errorsmod.Register(ModuleName, 1202, "Invalid depositor address")
	ErrInsufficientFunds                 = errorsmod.Register(ModuleName, 1203, "Insufficient funds")
	ErrDepositNotFound                   = errorsmod.Register(ModuleName, 1204, "Deposit not found")
	ErrInsufficientDepositAmount         = errorsmod.Register(ModuleName, 1205, "Amount is less than minimum deposit amount")
	ErrInvalidWinnerAddress              = errorsmod.Register(ModuleName, 1206, "Invalid winner address")
	ErrInvalidSponsorWinnerCombo         = errorsmod.Register(ModuleName, 1207, "A sponsor cannot designate another winner address")
	ErrInvalidDepositState               = errorsmod.Register(ModuleName, 1208, "Deposit is in an invalid state")
	ErrInvalidPoolAccountAddress         = errorsmod.Register(ModuleName, 1209, "Invalid pool module account address")
	ErrInvalidRestorerAddress            = errorsmod.Register(ModuleName, 1210, "Invalid restorer address")
	ErrPoolDrawNotFound                  = errorsmod.Register(ModuleName, 1300, "Pool draw not found")
	ErrPoolDrawNotDone                   = errorsmod.Register(ModuleName, 1301, "Cannot launch a new draw until the previous one is done")
	ErrInvalidDrawState                  = errorsmod.Register(ModuleName, 1302, "Invalid draw state")
	ErrInvalidDrawRetryAddress           = errorsmod.Register(ModuleName, 1303, "Invalid draw retry address")
	ErrPrizeNotFound                     = errorsmod.Register(ModuleName, 1400, "Prize not found")
	ErrInvalidPrizeState                 = errorsmod.Register(ModuleName, 1401, "Prize is in an invalid state")
	ErrInvalidPrizeAmount                = errorsmod.Register(ModuleName, 1402, "Prize amount cannot be less than 1")
	ErrInvalidDestinationAddress         = errorsmod.Register(ModuleName, 1500, "Invalid destination address")
	ErrInvalidWithdrawalDepositorAddress = errorsmod.Register(ModuleName, 1600, "Invalid withdraw depositor address")
	ErrDepositAlreadyWithdrawn           = errorsmod.Register(ModuleName, 1601, "Deposit has already been withdrawn")
	ErrInvalidWithdrawalState            = errorsmod.Register(ModuleName, 1602, "Invalid withdrawal state")
	ErrWithdrawalNotFound                = errorsmod.Register(ModuleName, 1603, "Withdrawal not found")
	ErrInvalidPacketCompletionTime       = errorsmod.Register(ModuleName, 1604, "Invalid packet completion time for withdrawal undelegate")
)
