name: Check formatting and import ordering

on:
  pull_request:
  workflow_dispatch:

jobs:
  formatcheck:
    name: Run format check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: "0"

      - name: Run make format-check
        run: |
          bash ./scripts/install_tools.sh
          make format-check
