name: Check linting

on:
  pull_request:
  workflow_dispatch:

jobs:
  lintcheck:
    name: Run linter check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --timeout 10m
